/* FIRST Team 1073's RobotBuilder (0.0.2) for WPILibExtensions ---
Do not mix this code with any other version of RobotBuilder! */
#ifndef BLING_BLING_H
#define BLING_BLING_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "../WPILibExtensions/WPILibExtensions.h"
#include "Colors.h"
class Bling_Bling: public Subsystem {
private:
	float duty_red;
	float duty_green;
	float duty_blue;
    void setLedColor(Colors* colors);
    Colors* blueLed;
    Colors* redLed; 
    Colors* greenLed;
    Colors* whiteLed;
    Colors* purpleLed;
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	DigitalOutput* red_Light;
	DigitalOutput* blue_Light;
	DigitalOutput* green_Light;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Bling_Bling();
	static const int BLUE = 0;
	static const int RED = 1;
	static const int GREEN = 2;
	static const int WHITE = 3;
	static const int PURPLE = 4;
	void lowerBrightness(int color);
	void raiseBrightness(int color);
	void InitDefaultCommand();
	void setLed(int color);
};
#endif
